[project]
name = "gateway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pylint>=3.3.7",
    "jedi>=0.19.2",
    "pika>=1.3.2",
    "flask>=3.1.1",
    "flask-pymongo>=3.0.1",
    "requests>=2.32.4",
]
