apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
data:
  AUTH_SVC_ADDRESS: "auth:5000"
  MONGO_USERNAME: mongoRoot
  MONGO_URI: mongodb:27017/
  MONGO_DATABASE_VIDEO: videos
  MONGO_DATABASE_MP3: mp3s