apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-configmap
data:
  MP3_QUEUE: "mp3"
  VIDEO_QUEUE: "video"
  SENDER_ADDRESS: "mydammy@gmail.com"
  SMTP_SERVER: "smtp.google.com"
  SMTP_PORT: 587