[project]
name = "auth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "flask-mysqldb>=2.0.0",
    "jedi>=0.19.2",
    "pyjwt>=2.10.1",
    "pylint>=3.3.7",
    "uvicorn>=0.35.0",
]
